name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8739cecd24e799463be2da92a301ead5485ea4d74c35f62051591479e1da0c2d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
