name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cf2cc15623dcc7352f593589677b647eb0c0657df9c8d36612bb46e7a06ce2d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
