name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a9e18e9d8ce87ad705b95271f337a3af9611ba8192105e6e7341805a3bab024"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
