name = "Vital"
author = "usevital, SkywardMC"
version = "3.0.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b81c9e9d9e6e21a9865a2dded0dfd77e7683d679b98fe5b0114eaed9a31f17e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
