name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.2+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e305fa998de8d54d0fc8e978625be4377abeda5445ab8e3ca4a15ed1bfb7e441"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
