name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "808c947aec9abf9a513370ac902e75fb0019bd945c36f7a859d04bdcde1640a2"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
