name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9442e90ab02b7e1f10b3601f2898b158965b801a25a462f230ef8948cfbebd5"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
