name = "Vital"
author = "usevital, SkywardMC"
version = "2.1.1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ac41446b1e12c6ed4fecbe717473c8ce82853d7c4e88bc6640d95dab570d5ed"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
