name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a032a1ee63906f4a779899ef8def5b10f9735f73a4e3d29537addc356c8750ce"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
