name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4befba4cff46c5bef28cb45602ccbc4940e81f099b17d3ac17a3932ebbc90670"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
