name = "Vital"
author = "usevital, SkywardMC"
version = "2.2.1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "913f2672d3ecb8a4d820269b92b1849f57bdd207cb2e7f5b20318707ed8f34a5"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
